name: whisper_flutter_plus
description: Ready to use whisper.cpp models implementation for iOS and Android
version: 0.0.2
homepage: https://github.com/krikristoophe/whisper_flutter_plus.git
repository: https://github.com/krikristoophe/whisper_flutter_plus.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.11.0"

dependencies:
  easy_dart_logger: ^1.0.1+1
  ffi: ^2.0.1
  ffmpeg_dart: ^0.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  plugin_platform_interface: ^2.0.2
  universal_io: ^2.2.0
  

dev_dependencies:
  build_runner: ^2.4.6
  ffigen: ^6.1.2
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true